sets = [
    {'id': 'sv8a', 'name': 'Super Electric Breaker', 'generation': 9},
    {'id': 'sv7a', 'name': 'Paradise Dracona', 'generation': 9},
    {'id': 'sv7', 'name': 'Stellar Miracle', 'generation': 9},
    {'id': 'sv6a', 'name': 'Night Wanderer', 'generation': 9},
    {'id': 'sv6','name': 'Mask of Change', 'generation': 9},
    {'id': 'sv5a', 'name': 'Crimson Haze', 'generation': 9},
    {'id': 'sv5k', 'name': 'Wild Force', 'generation': 9},
    {'id': 'sv5m', 'name': 'Cyber Judge', 'generation': 9},
    {'id': 'sv4a', 'name': 'Shiny Treasure Ex', 'generation': 9},
    {'id': 'sv4k', 'name': 'Ancient Roar', 'generation': 9},
    {'id': 'sv4m', 'name': 'Future Flash', 'generation': 9},
    {'id': 'sv3a', 'name': 'Raging Surf', 'generation': 9},
    {'id': 'sv3', 'name': 'Ruler of the Black Flame', 'generation': 9},
    {'id': 'sv2a', 'name': 'Pokemon 151', 'generation': 9},
    {'id': 'sv2p', 'name': 'Snow Hazard', 'generation': 9},
    {'id': 'sv2d', 'name': 'Clay Burst', 'generation': 9},
    {'id': 'sv1a', 'name': 'Triple Beat', 'generation': 9},
    {'id': 'sv1s', 'name': 'Scarlet', 'generation': 9},
    {'id': 'sv1v', 'name': 'Violet', 'generation': 9},
    {'id': 's12a', 'name': 'VSTAR Universe', 'generation': 8},
    {'id': 's12', 'name': 'Paradigm Trigger', 'generation': 8},
    {'id': 's11a', 'name': 'Incandescent Arcana', 'generation': 8},
    {'id': 's11', 'name': 'Lost Abyss', 'generation': 8},
    {'id': 's10b', 'name': 'Pokemon GO', 'generation': 8},
    {'id': 's10a', 'name': 'Dark Phantasma', 'generation': 8},
    {'id': 's10d', 'name': 'Time Gazer', 'generation': 8},
    {'id': 's10p', 'name': 'Space Juggler', 'generation': 8},
    {'id': 's9a', 'name': 'Battle Region', 'generation': 8},
    {'id': 's9', 'name': 'Star Birth', 'generation': 8},
    {'id': 's8b', 'name': 'VMAX Climax', 'generation': 8},
    {'id': 's8a', 'name': '25th Anniversary Collection', 'generation': 8},
    {'id': 's8', 'name': 'Fusion Arts', 'generation': 8},
    {'id': 's7r', 'name': 'Blue Sky Stream', 'generation': 8},
    {'id': 's7d', 'name': 'Towering Perfection', 'generation': 8},
    {'id': 's6a', 'name': 'Eevee Heroes', 'generation': 8},
    {'id': 's6k', 'name': 'Jet Black Spirit', 'generation': 8},
    {'id': 's6h', 'name': 'Silver Lance', 'generation': 8},
    {'id': 's5a', 'name': 'Matchless Fighter', 'generation': 8},
    {'id': 's5r', 'name': 'Rapid Strike Master', 'generation': 8},
    {'id': 's5i', 'name': 'Single Strike Master', 'generation': 8},
    {'id': 's4a', 'name': 'Shiny Star V', 'generation': 8},
    {'id': 's4', 'name': 'Electrifying Tackle', 'generation': 8},
    {'id': 's3a', 'name': 'Legendary Pulse', 'generation': 8},
    {'id': 's3', 'name': 'Infinity Zone', 'generation': 8},
    {'id': 's2a', 'name': 'Explosive Flame Walker', 'generation': 8},
    {'id': 's2', 'name': 'Rebellion Crash', 'generation': 8},
    {'id': 's1a', 'name': 'VMAX Rising', 'generation': 8},
    {'id': 's1w', 'name': 'Sword', 'generation': 8},
    {'id': 's1h', 'name': 'Shield', 'generation': 8}
]
